name: Rust ARMv7 build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.toolchain }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: thumbv7em-none-eabihf
          override: true
      - name: cargo build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Create Issue Action if failed
        uses: nashmaniac/create-issue-action@v1.1
        if: failure() 
        with:
          title: Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: worflow-failed
          body: Workflow failed for commit ${{github.sha}} [see details](${{github.server_url}}/${{github.repository}}/runs/${{github.run_number}}?check_suite_focus=true)

